language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: Mr+HJvvcBhbyrttROXAxEWFpWA5YblqiqKaX+fK9oGxMIZdksysrlwIT07wYnXKluf1VdShrlrtacXtfhCmAKuDDfhRT9eLucpg9Z9fL07neWyESagb4Q3sqZ2Xd+SpCD6SX6j7x2RRLego7o0QRIA4n6GxUL+M/eEny9BeYcDKId7YDAj+YOUg5BYdGMjXSD0eEWwhx9zRNqpK9ruGCgxQ3cSOANSdDbvcO2vWF9ZPngr13BBx5pRBiXvC4YmS2uVgj0tE4fnYdyiHIqETwFn/4pg/FqyJ6NXaIB45eVL49IaO2WBCV5nnDuEpDHsyrWcSwZKIfV1KtnEdbnFpkUtQa/Ip8cjOrR+DdVrzjKw6KRbKXOxbwvDNCGTIJlhY9zO7hZz3oE1ChkdOmH0EzH529Hr/f/45I++mqozNgd+l324f8++UBdvIZvxa2ycnHuB/8+hsxU0yG5d4AOF17crzJN7sIwrsqOhjiw6n/KBhgZ19ISdXcSFsRtXRCBVLaRGGitlzThP1oYbQG2A4acIOTnbuLhsw9XCExCP3Kjgqfpe1LqVGDw++6NNNj1wNmpLxrOqajbxOn+bQ4UPXIVxVStEpMdvO2zGFaBK90S//hJVLqcnnBeT+mRurmhBvFRFpqGQduOXllWk1RvmlMLdrn5J505E6z1vPeE5C8CKU=
  on:
    tags: true
    all_branches: true
