language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: l/gJQzS5ek1LyOou6JrugAcIROVIcr6o78YEq/zloNXuild7rTNbb/2SYLxQTe2ubA/eiANEUWQ/8cmJkAxYuFtGV3y9KxDMD9nRwMDI8CauRL8ayN79SZRf81wkYQziPQQdD93sy+ULpKRloi0EbqRW9pne7p0SpYZIRkdqCaT9K2rulOua8Q65HnbG5II2zxg6yqGI1OQifQhNHHGWv0hg60k44zaiYSoQ6TMVvroSqdWnq9XR9fw5DuksVJzymFsO9onqs6QyTw5BYmLWQiHeFwdga1fF7AXIrxaKbOwJzkymjNo8J+5PEbRm6U+epyHSFVoXOQnZhvm9YSb+PhEyk6Q0NIvjqAb5FO0rxlfInJAK/kbqLwdWSKg5LXTY22w9UGcUUTnZ5/Y3YtFbv5pAwz1DoMWe9b8GOzPxXVdF2XW7CfrJOE6XkQcGCYgQml1AFpIUCst5T4kowKrVOIQDGAJcMrFk4unz9nrTmYub4yvd4aRazvgrfyb5nZ6lc8FFPny5XOKb4xC9kwyPccIS+tz8LW/FYwwLAljlxJF+CxKyhCYxq4uUkhhpm4uQZd1M2spn+i0qP/Jp4YHFXw5p9iAZM3zS9bQwV/ZQjskndh/0hHnMmcp829K41IVqUoEuU+hbM0LOwMh/RrntklnBMpa1ssbJMYoMKZAuzJ0=
  on:
    tags: true
    all_branches: true
