language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: o+BkRNAFvNRuFLC/zBUhbCmD46xOKiiUCX8xc5iNhUgJJ303R0S7IsG9wHHOypaAK20LLhm0vhdy8G22LpJSHlWNAvHwpXv33q5/D/IBGWv1T5NvyrJc7Al6iXFx4JFlz77oqX9LqJ1BGCZudP2O5JS5zKHexa7a26jyx0Kqh6rposBqeWUXjDr1rv277EykZDmzS5YpWSMhf8ndmMepJ/RtnrbiXlmTv4F2RVXdh2bTU57lSmYq/2jJ6K0t6FK8Kv58P9wURXruDemlUTNsbHTU9yocL9DpDBuRrPCgRmS200gGorPB7SN5cU8YNWuz6DIzx/23pH/+daPrs9Aqr/K4tiBamOjURVkqCuuMWUjmIpLo+LWEkOXaui8UWvOyDnw+od7KJvWiI0XCYDOx6zLBUqJl1V1kkSsiTaLTpNWqAYbZI9ol9pSJI7hh79l4yA80Hm6BQkVHfx/IA4X12CWpS+w3q1digczk7CqimcgqHTwnh9fHJdrSlJmIqxZ/rm+/3gfQR7b8XK+JQ/JmNfB4XyCxvDbSETG6q51+HF0x/6q8CbYMNpdakyTrKrGKJ1bOmsZGmgEH5AJEojfkrRnHc0VSwWMjSwtgGRSb/UEkNMdasaWplPoa46PDNXiXVziVWQGzLbB/2lwSAZbtGAXhiLMRzY1BWaCZ2x4VUeU=
  on:
    tags: true
    all_branches: true
