language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: ynQqXTmlCgR+x86MCIdGrEbCPIi1KDy5pMyGYKxTeAPItZUaX8jgjlK3PFwIyDxOho0KLw8nq+ia04APB9lCCnM3RbUnQqQPtTrVVhjGH/+ptd1rC5zSzzaEei8iQQ6a4DXkLPcjEBAHGLvtqjzgQMBJ0BG7+vL0pKt73Fx5OxK+RVxoP6uU42UNOdSQrJDLVqfS+5iBgKmLin6t5lW5I4b9tni+EJzPrRKKCitY93jAZJ7O1PD7o7vBxrbKnUjk5i27dYWj0NQp1vRFi3+UGM74SkYnJHsC0/9d61qK1+BTWhbUKUhXcrKEC0B283hKYql9ewVSg45+3i1yiUawmvG8xtG4ROX8DgKOtBf/iuv+gUwJrkMrDUGyLva1mqtASLhTDVLDzSd9XsxHWSN83thIpBLb4shlAsqj4u/2B3xO+iQ2xwP6XDEY51VMslpJZu6O5BoorHr1u+j9VwE04qErJsTCYU6w+i887caGeQm9GhNGTh2Gtgbu2Xgk+kHwtsyZylbhpVJQ74ci4SNpUB3n53Ju3WpBJBDJsglTcqMA6yDkUZnjRfcO+ZMK3K9plLKxYZeG2lJQYzMTqstj7LkhRTIaIEX2q4X88J2iHXwDTmdqfAS6IFxgU4X8l3C/6IZEPuC5tXfM4s6Wa1ywgyUlOk5JDh4PM9BIntpMnDI=
  on:
    tags: true
    all_branches: true
