language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: NYnqqyRxTNOHVjXCTb9TofQtxm+c3G8BQbtAK2OQzgESZud0OqFosFSXUkHbZLtvJLChPh5n57ikGxDydzSZnlNASAue3lT6R5yeSzNeIhI43kdMpnA9Exm2cNYZYF9Oz8wqeiifJsCMJsQwWk/JTc3hosqG5KnbaInvlaQBGWkXCViFxPFv/OwX682O9mV7k9vNFL0cAbhHYRSCsIA/CAC3S1HhQDKEJ1D0IKdJVrvjFcCLGhmlHBx3pVhNxpej2xpQ/gnpse9KZXaxVGcPjyzUbdDgmu/Qts+7AKPGcI3/0DZV5O0wp5TxZdwuiVU+qosw7wNIPWS082Ue2I7jAWnaElx87NrjFOd5SmB6F2b8ZgtqiQJUks7vs9sHi3XSRqwe7DQL/absctLdA3eVoHTEnw9+BW9Tyn5uoDwA9xvd5C9cF2DXvDLOrbS+w5UCgs50YIsaJsUzsME/l29VOIhoXO2YNPyWugxUZKOghB5dn6EjPGN4IEGb2nLwVqEPLE9fapw/PXsm/koxyVienw5KaQtbjzi/bSYEmVW4FzPD4hxV7gjSKLXLcVfX8EaD+vV636KExnE3/g/nE21AZwPoZjekCDiMoYwd7CAAPeflH8tKDtMatjMWcE+cnfLDI4R77x/acez/fA5aroYeoo8zBMPqduy1dawhqq3Qsrg=
  on:
    tags: true
    all_branches: true
