language: python
python: 3.7
script: skip
deploy:
  provider: pypi
  user: kpn-digital
  skip_cleanup: true
  password:
    secure: HvvAhJndD7EcQako7UrEquAIy88zONvru32sq8uZqgDd4YMLmvBuB1p617bw7U8pGasWgkPvlq9uofSLGOvmZfgQNqnjIP2gXWfD4sk+hH+wpJ79H/WFp20R0KPmvo87B1Yu2lpixBsAhQ513dtWhjP4UjF/5Po/lb6bWPcwqYl/rXfRK/XLVfzDFvMAsgvs5q4HY7320PwFV0bqFDAc3v99qs+AKEbsqRj+V/COkIT6FtD3rGv94yryCdGMzjr7BvBh9TLk3iWEAqqfhUF0H7z7tJzwsKvl6U3GOYO6WNFP2e/Ukgc4esA6XHKlLREBr8u9WVdIaJtLO5xClK0KKlYMlPMfc0DNsL2RT+NywVwaovPwLiQ+jj4RO9V3BQohCoC3Wy0AV4L63oHFOPhWbGNNHl88fTUWpxup3B7LOXeTndUIH74abtMiqKsa7lkBNXBHsqfCqM6Lk/Lzh00Vy9Yb9QMCyB5ttLqqdrIWB4qa7yDa4bzfiqP2SoKpA2wdEaVPh/j4M8rXlmGJq9HPPEBfjwle+xy0KgA7R791b6PfcYwc1zQjgOAGLDp9+lW1qgN26GicWgOg0xoHie4skslkZrzGQdAM6vgsIb5V1JnnOI4jNSKYEBILAkdCZJDIGseTz32Re1aPjdOxwWdrzoSKi3JXj5d+XE0NGacMOGg=
  on:
    tags: true
    all_branches: true
